# docker-compose.yml
version: '3.8'

services:
  nginx-rtmp-service:
    build:
      context: ./nginx-rtmp # O Dockerfile para este serviço está em ./nginx-rtmp
    container_name: nginx-rtmp-receiver
    restart: always
    ports:
      - "1935:1935" # Apenas a porta RTMP é exposta para o celular

  ffmpeg-streamer-service:
    build:
      context: ./ffmpeg-streamer # O Dockerfile para este serviço está em ./ffmpeg-streamer
    container_name: ffmpeg-http-flv-streamer
    restart: always
    ports:
      - "8081:8080" # Porta HTTP-FLV para o Google Colab:
                   # 8081 na VPS (público) -> 8080 no container ffmpeg (interno)
    
    # Garante que o ffmpeg só inicie depois que o nginx-rtmp-service estiver UP
    depends_on:
      - nginx-rtmp-service
