version: '3.8'

services:
  nginx-rtmp:
    build: ./nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"   # RTMP
      - "8080:80"     # HTTP, se quiser usar HLS depois
    restart: unless-stopped
    networks:
      - rtmp_net

networks:
  rtmp_net:
    driver: bridge
