# docker-compose.yml
version: '3.8'

services:
  rtmp-server:
    volumes:
      - hls-data:/var/hls
    networks:
      - easypanel-network # Substituir pelo nome da rede do seu projeto EasyPanel

  web-player:
    volumes:
      - hls-data:/usr/share/nginx/html
    networks:
      - easypanel-network # Substituir pelo nome da rede do seu projeto EasyPanel
    # As configurações de domínio e proxy para este serviço serão feitas na UI do EasyPanel

volumes:
  hls-data:

networks:
  easypanel-network:
    external: true
