version: '3.8'

services:
  # Nosso serviço único que agora suporta SRT
  streaming-service:
    build: .
    networks:
      - easypanel
    # Aumenta o limite de memória compartilhada, útil para streaming
    shm_size: '2gb'

networks:
  easypanel:
    external: true
