version: '3.9'
services:
  srs:
    image: ossrs/srs:5
    container_name: srs-media-server
    restart: always
    ports:
      - "1935:1935"
      - "8080:8080"
      - "1985:1985"
      - "10080:10080/udp"
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
