version: '3.8'

services:
  # Nosso serviço único que faz tudo
  streaming-service:
    build: .
    # Não defina 'ports' aqui para 80 ou 443. O EasyPanel/Traefik gerencia isso.
    networks:
      - easypanel # Nome padrão da rede, confirme na sua UI do EasyPanel se necessário

networks:
  easypanel:
    external: true
