# docker-compose.yml
version: '3.8'

services:
  nginx-rtmp:
    build: ./nginx-rtmp
    ports:
      - "1935:1935" # Porta do RTMP
      - "8080:8080" # Porta para estatísticas (opcional)
    container_name: nginx-rtmp
    restart: always
