FROM python:3.9-slim-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y libgl1-mesa-glx

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ml_processor.py .

CMD ["python", "ml_processor.py"]
